# Generated by Django 5.1.2 on 2024-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.ImageField(max_length=15, null=True, upload_to='')),
                ('namber', models.CharField(max_length=13, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('info', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
