# Generated by Django 5.1.3 on 2026-02-05 05:33

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boshqarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')])),
                ('jshir', models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message="JSHIR 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unvon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')])),
                ('jton', models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message="JTON 8 ta raqamdan iborat bo'lishi kerak", regex='^\\d{8}$')])),
                ('lavozimi', models.CharField(blank=True, max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bolim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bolim')),
                ('boshqarma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.boshqarma')),
                ('ishjoylari', models.ManyToManyField(blank=True, related_name='ishjoylari', to='api.boshqarma')),
                ('unvon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unvon')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bolim',
            name='boshqarma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolimlar', to='api.boshqarma'),
        ),
        migrations.CreateModel(
            name='ArizaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('imeiApi', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message="imeiApi 15 ta raqamdan iborat bo'lishi kerak", regex='^\\d{15}$')])),
                ('last_simcard', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('shakl1', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('yaratildi', 'Yaratildi'), ('qidiruvda', 'Qidiruvda'), ('topild', 'Topildi'), ('yopildi', 'Yakunlandi')], default='yaratildi', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuruhgaOid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('device_type', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JinoyatIshiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('jinoyat_raqami', models.CharField(db_index=True, max_length=255)),
                ('fish', models.CharField(max_length=255)),
                ('jshir', models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message="JSHIR 14 ta raqamdan iborat bo'lishi kerak", regex='^\\d{14}$')])),
                ('info', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('ochilgan', 'Yangi'), ('qaytarilgan', 'Qaytarilgan'), ('sud', 'Sudga chiqarildi'), ('yopildi', 'Yopilgan')], default='ochilgan', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nomlanishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('namen', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rusumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XisobgaQoyishSababi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sabab_name', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XisobTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tur_nomi', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('imeiApi', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="imeiApi 15 ta raqamdan iborat bo'lishi kerak", regex='^\\d{15}$')])),
                ('last_simcard', models.CharField(blank=True, max_length=255, null=True)),
                ('soni', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('zavod', models.CharField(blank=True, max_length=255, null=True)),
                ('rangi', models.CharField(blank=True, max_length=255, null=True)),
                ('tegishlilik', models.CharField(blank=True, max_length=255, null=True)),
                ('xususiyatlari', models.TextField(blank=True, null=True)),
                ('ishlab_chiqarilgan_yili', models.PositiveIntegerField(blank=True, null=True)),
                ('device_rasmmi', models.ImageField(blank=True, null=True, upload_to='device_rasmmi')),
                ('xujat_raqami', models.CharField(blank=True, max_length=255, null=True)),
                ('xujat_yaratilgan_sana', models.DateTimeField(auto_now_add=True, null=True)),
                ('tashkilot', models.CharField(blank=True, max_length=255, null=True)),
                ('xudud', models.CharField(blank=True, max_length=255, null=True)),
                ('organ', models.CharField(blank=True, max_length=255, null=True)),
                ('modda', models.CharField(blank=True, max_length=255, null=True)),
                ('qism', models.CharField(blank=True, max_length=255, null=True)),
                ('band', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gruhga_oid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guruhgaoid')),
                ('nomlanishi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nomlanishi')),
                ('rusumi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rusumi')),
                ('sababi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.xisobgaqoyishsababi')),
                ('xisob_turi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.xisobturi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
